config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: "registrations" }

  # set a devise login to root
  devise_scope :user do
      root to: "devise/sessions#new"
  end

  resources :projects, only: [:index, :new, :create, :show] do
    resources :people, only: [:create, :destroy]
    resources :boards, only: [:index, :show] do
      get :backlog, on: :member
      get :issue, on: :member
      get "issue/:id/edit_issue" => "boards#edit_issue", as: :edit_issue

      resources :lists, only: [:index, :show]
      resources :sprints, only: [:create, :edit, :update, :destroy] do
        put :complete_sprint, on: :member
        get :sprint_start, on: :member
      end
      resources :cards, only: [:create, :update, :destroy]
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/list.rb
class List < ApplicationRecord

  # okay relation
  has_many :cards
  belongs_to :board

  belongs_to :sprint, optional: true

  def self.list_cards param
    lists = Board.find(param).lists
    result = lists.map do |list|
      {
          title: list.title,
          cards: list.cards.where(status: 1)
      }
    end

    return result
  end

  def self.list_sprint_date param
    sprints = Board.find(param).sprints.find_by(status: 1)

    if sprints
      remaining = sprints.duration - (DateTime.now.to_date - sprints.start.to_date).to_i
      result = remaining.to_s + " days remaining"
    else
      result = "0 days remaining"
    end

    return result
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  layout 'main_layout'

  def index
    get_parameter

    @list = List.list_cards(params[:board_id])
    @list_date = List.list_sprint_date(params[:board_id])
    @sprint = Board.find(params[:board_id]).sprints.find_by(status: 1)

  end

  private

  def get_parameter
    @project_id = params[:project_id]
    @board_id = params[:board_id] ? params[:board_id] : params[:id]
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/index.html.erb
<div class="row">
  <div class="col-md-12">

    <div class="row">
      <div class="col-md-6 col-md-offset-6">
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li class="new">
              <%= link_to "", class: "text-custom", style: "padding:8px;" do %>
                <%= fa_icon("bell", text: @list_date) %>
              <% end %>
            </li>
            <li class="nohover">
              <% if role_view(session[:role]) %>
                <% if @sprint.present? %>
                  <%= link_to "Complete sprint", complete_sprint_project_board_sprint_path(params[:project_id], params[:board_id], @sprint), class: "btn btn-success", style: "padding:6px 12px;margin-right:10px;", method: :put %>
                <% end %>
              <% end %>
            </li>
            <li class="dropdown">
              <button type="button" name="button" class="dropdown-toggle btn btn-default" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= fa_icon("ellipsis-h") %>
              </button>
              <ul class="dropdown-menu" style="margin-top:7px;">
                <li><%= link_to "Create list", "" %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="main-list">
      <div class="row">
        <div class="col-md-12">
          <div class="row">
            <% @list.each do |list| %>
              <div class="col-md-3">
                <div style="background-color:#D0D0D0;padding-bottom:5px;width:262px;margin-top:10px;float:left;">
                  <label class="label label-success text-uppercase" style="margin-left:7px;margin-top:7px;float:left;display: block;"><%= list[:title] %></label>
                  <% list[:cards].each do |cards| %>
                    <div class="card" style="margin: 13px 7px;background-color: #fff96b;width: 248px;padding:5px;float:left;">
                      <%= cards.title %>
                      <div class="text-uppercase">
                        <label class="label label-warning"><%= cards.type_issue.name %></label>
                        <label class="label label-primary"><%= cards.priority.name %></label>
                      </div>

                      <div style="margin-top:30px;text-align:right;">
                        <%= link_to project_board_edit_issue_path(@project_id, @board_id, cards) do %>
                          <%= fa_icon("arrow-right") %>
                        <% end %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>