config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: "registrations" }

  # set a devise login to root
  devise_scope :user do
      root to: "devise/sessions#new"
  end

  resources :projects, only: [:index, :new, :create, :show] do
    resources :people, only: [:create, :destroy]
    resources :boards, only: [:index, :show] do
      get :backlog, on: :member
      get :issue, on: :member
      get "issue/:id/edit_issue" => "boards#edit_issue", as: :edit_issue

      resources :lists, only: [:index, :show]
      resources :sprints, only: [:create, :edit, :update, :destroy] do
        put :complete_sprint, on: :member
        get :sprint_start, on: :member
      end
      resources :cards, only: [:create, :update, :destroy]
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user

  # okay relation
  has_many :boards

  has_many :people
  has_many :users, :through => :people

  after_create :create_board

  def create_board
    @board = self.boards.new
    @board.name = self.key

    @board.save
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    layout 'main_layout'

    def index
      @project = Project.where(user_id: current_user.id)
      session[:role] = 1

      if @project.empty?
        @person = User.find(current_user.id).people
        selection_project = @person.pluck(:project_id)

        @project = Project.where(id: selection_project)
        session[:role] = 2
      end
    end

    def new
      @project = Project.new
    end

    def create
      project = User.find(current_user.id).projects.new(resource_params)

      if project.save
        redirect_to projects_path
      end
    end

    def show
      @project = Project.find(params[:id])

      # create
      @person = Person.new

      @users = @project.people.pluck(:user_id)
      @userlist = User.where.not(id: @users)
                      .where('id != ?', current_user.id)

      @boards = @project.boards.all
      @member = @project.people.all
    end

    private

    def resource_params
      params.require(:project).permit(:name, :key)
    end
end

app/views/projects/index.html.erb
<div id="main-project">
  <div class="row">
    <div class="col-md-12">
      <% if role_view(session[:role]) %>
        <%= link_to new_project_path, class: "btn btn-default" do %>
          <%= fa_icon "plus-circle" %><span>Create project</span>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-12">
      <div class="row">
        <% @project.each do |project| %>
          <div class="col-md-3">
            <div class="project-card">
              <h5><%= project.name %></h5>
              <%= link_to project_path(project), class: 'btn btn-sm btn-default' do %>
                <%= fa_icon "arrow-right" %>
              <% end %>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div id="main-project">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= form_for @project do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, autocomplete: 'off', id: 'name-project', class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :key %>
          <%= f.text_field :key, autocomplete: 'off', id: 'key-project', class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.submit 'Create', class: 'btn btn-custom' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div id="main-project">
  <div class="row">
    <div class="col-md-12">
      <% if role_view(session[:role]) %>
        <%= link_to new_project_path, class: 'btn btn-default' do %>
          <%= fa_icon "plus-circle" %><span>Create board</span>
        <% end %>
      <% end %>
    </div>
    <div class="col-md-12">
      <div class="row">
        <% @boards.each do |board| %>
          <div class="col-md-3">
            <div class="board-card">
              <h5><%= board.name %></h5>
              <%= link_to project_board_path(board), class: 'btn btn-sm btn-default' do %>
                <%= fa_icon "arrow-right" %>
              <% end %>
            </div>
          </div>

        <% end %>
      </div>
    </div>
    <% if role_view(session[:role]) %>
      <div class="col-md-6">
        <hr>
      </div>

      <div class="col-md-12">
        <div class="row">
          <div class="col-md-6">
            <%= form_for [@project, @person] do |f| %>
              <div class="form-group">
                <%= f.label :user_id %>
                <%= f.collection_select :user_id, @userlist, :id, :email, {include_blank: true}, {class: "form-control"} %>
              </div>
              <div class="form-group">
                <%= f.submit "Add member", class: "btn btn-custom" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-12">
        <div class="row">
          <div class="col-md-6">
            <table class="table table-bordered table-hover">
              <thead>
              <tr class="text-uppercase">
                <th>Email</th>
                <th>Action</th>
              </tr>
              </thead>
              <tbody>
              <%= empty_table(@member, 2) %>
              <% @member.each do |member| %>
                <tr>
                  <td><%= member.user.email %></td>
                  <td>
                    <%= link_to project_person_path(@project, member), class: "btn btn-xs btn-danger btn-custom-danger", method: :delete, data: {confirm: "Are you sure?"} do %>
                      <%= fa_icon("times") %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/test.html.erb
<div class="row">
  <div class="col-md-12">
    <%= @users.inspect %>
  </div>
</div>
<br>
<div class="row">
  <div class="col-md-12">
    <%= @member.inspect %>
  </div>
</div>