config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: "registrations" }

  # set a devise login to root
  devise_scope :user do
      root to: "devise/sessions#new"
  end

  resources :projects, only: [:index, :new, :create, :show] do
    resources :people, only: [:create, :destroy]
    resources :boards, only: [:index, :show] do
      get :backlog, on: :member
      get :issue, on: :member
      get "issue/:id/edit_issue" => "boards#edit_issue", as: :edit_issue

      resources :lists, only: [:index, :show]
      resources :sprints, only: [:create, :edit, :update, :destroy] do
        put :complete_sprint, on: :member
        get :sprint_start, on: :member
      end
      resources :cards, only: [:create, :update, :destroy]
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  # okay relation
  belongs_to :project
  has_many :lists
  has_many :sprints

  has_many :cards

  after_create :create_list

  def create_list
    default_list = ['todo', 'inprogress', 'test', 'done']
    default_list.each_with_index do |item, index|
      list = self.lists.new
      list.title = item
      list.sort_order = index

      list.save()
    end

  end

  def self.sprint_cards param
    sprints = Board.find(param).sprints.where.not(status: 2)
    result = sprints.map do |sprint|
      {
          id: sprint.id,
          name: sprint.name,
          status: sprint.status,
          cards: sprint.cards
      }
    end

    return result
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  layout 'main_layout'

  # main (board)
  def show
    get_parameter
  end

  # backlog
  def backlog
    get_parameter

    @board = Board.sprint_cards(params[:id])
    @sprint_first = @board.first
    @sprint = @board

    @backlog = Board.find(params[:id]).cards.where(sprint_id: 0)

    # -- still default type_issue --
    @typeissue = TypeIssue.all
    # ------------------------------
  end

  # create issue
  def issue
    get_parameter

    @card = Card.new

    get_issue_default
    # if this finish go to "backlog" again ^ finish
  end

  def edit_issue
    get_parameter
    @card = Card.find(params[:id])

    get_issue_default
    # it's for edit
  end

  private

  def get_parameter
    @project_id = params[:project_id]
    @board_id = params[:board_id] ? params[:board_id] : params[:id]
  end

  def get_issue_default
    # still default ---
    @typeissue = TypeIssue.all
    @priority = Priority.all
    # still default ---

    # @board_id = params[:id]
    @board = Board.find(@board_id)
    @list = @board.lists.all
    @sprint = @board.sprints.where.not(status: 2)

    @project = @board.project

    # fix assign list here !
    @people = @board.project.people
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form_issue.html.erb
<%= form_for [@project, @board, @card], :html => {id: "form-issue", enctype: "multipart/form-data"} do |f| %>
  <div class="form-group">
    <div class="row">
      <div class="col-md-6">
        <%= f.label "Status" %>
        <%= f.collection_select :list_id, @list, :id, :title, {}, {:class => "form-control text-uppercase"} %>
      </div>
      <div class="col-md-6">
        <%= f.label "Issue" %>
        <%= f.collection_select :type_issue_id, @typeissue, :id, :name, {}, {:class => "form-control text-uppercase"} %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.cktext_area :description, class: 'someclass', ckeditor: {language: 'en', toolbar: 'mini'} %>
  </div>

  <div class="form-group">
    <%= f.label :attachment, style: "display:block;" %>
    <% if @card.attachment.present? %>
      <%= image_tag(@card.attachment.to_s, width: "260px", height: "140px", style: "display:block;margin-bottom:10px;") %>
    <% end %>
    <%= f.file_field :attachment %>
  </div>

  <div class="form-group">
    <%= f.label :priority_id %>
    <%= f.collection_select :priority_id, @priority, :id, :name, {}, {:class => "form-control text-uppercase"} %>
  </div>

  <div class="form-group">
    <%= f.label "Send to" %>
    <%= f.collection_select :sprint_id, @sprint, :id, :name, {:include_blank => 'Backlog'}, {:class => "form-control text-uppercase"} %>
  </div>

  <div class="form-group">
    <%= f.label "Assign to" %>
    <%= f.collection_select :assign_to, @people, :id, :name_with_initial, {:include_blank => true}, {:class => "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label "Due Date" %>
    <%= f.date_field :duedate, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-issue' %>
  </div>
<% end %>

app/views/boards/backlog.html.erb
<div id="main-sprint">
  <% if @sprint.present? %>
    <% @sprint.each do |sprint| %>
      <div class="main-sprint">
        <div class="row">
          <div class="col-md-6">
            <h5><%= sprint[:name] %></h5>
          </div>
          <div class="col-md-6">
            <% if role_view(session[:role]) %>
              <div class="row">
                <div class="col-md-12">
                  <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                      <li>
                        <% if show_sprint_start(sprint[:id], @sprint_first[:id], @sprint_first[:status]) %>
                          <%= link_to "Start", sprint_start_project_board_sprint_path(@project_id, @board_id, @sprint_first[:id]), class: "btn btn-default btn-custom-sprint" %>
                        <% end %>
                      </li>
                      <li class="dropdown">
                        <button type="button" name="button" class="dropdown-toggle btn btn-default" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                          <%= fa_icon("gear") %>
                        </button>
                        <ul class="dropdown-menu">
                          <li><%= link_to "Edit sprint", edit_project_board_sprint_path(@project_id, @board_id, sprint) %></li>
                          <li><%= link_to "Delete sprint", project_board_sprint_path(@project_id, @board_id, sprint), method: :delete, data: {confirm: "Are you sure?"} %></li>
                        </ul>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <table class="table table-striped" style="margin-top:15px;">
              <%= empty_table(sprint[:cards], 4) %>
              <% sprint[:cards].each do |card| %>
                <tr>
                  <td>
                    <label class="label label-warning"><%= card.title_issue.upcase %></label>
                  </td>
                  <td><%= card.title %></td>
                  <td>
                    <label class="label label-primary"><%= card.title_priority.upcase %></label>
                  </td>
                  <td>
                    <div class="collapse navbar-collapse">
                      <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                          <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <%= fa_icon("ellipsis-h") %>
                          </a>
                          <ul class="dropdown-menu">
                            <li>
                              <!-- # edit issue -->
                              <%= link_to project_board_edit_issue_path(params[:project_id], params[:id], card) do %>
                                Edit card
                              <% end %>
                            </li>
                            <li>
                              <!-- # destroy issue -->
                              <%= link_to project_board_card_path(params[:project_id], params[:id], card), method: :delete, data: {confirm: "Are you sure ?"} do %>
                                Delete card
                              <% end %>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </div>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>

<div id="main-backlog">
  <div class="row">
    <div class="col-md-6">
      <h5>Backlog</h5>
    </div>
    <div class="col-md-6">
      <% if role_view(session[:role]) %>
        <%= link_to "Create sprint", project_board_sprints_path(@project_id, @board_id), class: "btn btn-primary", style: "float:right;width:140px;", method: :post %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped" style="margin-top:15px;">
        <%= empty_table(@backlog, 2) %>
        <% @backlog.each do |backlog| %>
          <tr>
            <td>
              <label class="label label-warning"><%= backlog.title_issue.upcase %></label>
            </td>
            <td><%= backlog.title %></td>
            <td>
              <label class="label label-primary"><%= backlog.title_priority.upcase %></label>
            </td>
            <td>
              <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                  <li class="dropdown">
                    <a href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      <%= fa_icon("ellipsis-h") %>
                    </a>
                    <ul class="dropdown-menu" style="margin-top:7px;">
                      <li>
                        <!-- # edit issue -->
                        <%= link_to project_board_edit_issue_path(params[:project_id], params[:id], backlog) do %>
                          Edit card
                        <% end %>
                      </li>
                      <li>
                        <!-- # destroy issue -->
                        <%= link_to project_board_card_path(params[:project_id], params[:id], backlog), method: :delete, data: {confirm: "Are you sure ?"} do %>
                          Delete card
                        <% end %>
                      </li>
                    </ul>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= link_to "Create issue", issue_project_board_path(@project_id, @board_id), style: "width:140px;", class: "btn btn-info" %>
    </div>
  </div>
</div>

app/views/boards/edit_issue.html.erb
<div class="col-md-12">
  <%= render 'boards/form_issue', :layout => 'main_layout' %>
</div>

app/views/boards/issue.html.erb
<div class="col-md-12">
  <%= render 'boards/form_issue', :layout => 'main_layout' %>
</div>