config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: "registrations" }

  # set a devise login to root
  devise_scope :user do
      root to: "devise/sessions#new"
  end

  resources :projects, only: [:index, :new, :create, :show] do
    resources :people, only: [:create, :destroy]
    resources :boards, only: [:index, :show] do
      get :backlog, on: :member
      get :issue, on: :member
      get "issue/:id/edit_issue" => "boards#edit_issue", as: :edit_issue

      resources :lists, only: [:index, :show]
      resources :sprints, only: [:create, :edit, :update, :destroy] do
        put :complete_sprint, on: :member
        get :sprint_start, on: :member
      end
      resources :cards, only: [:create, :update, :destroy]
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  mount_uploader :attachment, AttachmentUploader

  belongs_to :board
  belongs_to :sprint, optional: true

  belongs_to :list
  belongs_to :priority
  belongs_to :type_issue

  def title_priority
    self.priority.name
  end

  def title_issue
    self.type_issue.name
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def create
    @card = Card.new(resource_params)
    @card.sprint_id = 0
    @card.board_id = params[:board_id]
    @card.created_by = current_user.id

    if @card.save
      redirect_to backlog_project_board_path(params[:project_id], params[:board_id])
    end

    puts @card.errors.full_messages
  end

  def destroy
    @card = Card.find(params[:id])
    if @card.destroy
      redirect_to backlog_project_board_path(params[:project_id], params[:board_id])
    end
  end

  def update
    @card = Card.find(params[:id])
    @card.created_by = current_user.id

    if @card.update(resource_params)
      redirect_to backlog_project_board_path(params[:project_id], params[:board_id])
    end
  end

  private

  def resource_params
    # add assign_to & user_id change created_by
    params.require(:card).permit(:list_id, :type_issue_id, :title, :description, :attachment, :priority_id, :sprint_id, :created_by, :assign_to, :duedate)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/create.html.erb
<h1>Cards#create</h1>
<p>Find me in app/views/cards/create.html.erb</p>

app/views/cards/edit.html.erb
<div class="row">
  <div class="col-md-12">

    <% @sprint.each do |sprint| %>
      <div class="main-sprint">
        <div class="row">
          <div class="col-md-6">
            <h4><%= sprint.name %></h4>
          </div>
          <div class="col-md-6">
            <div class="row">
              <div class="col-md-12">
                <div class="collapse navbar-collapse">
                  <ul class="nav navbar-nav navbar-right">
                    <li style="margin-right:10px;">
                      <button type="button" class="btn btn-success">
                        Start sprint
                      </button>
                    </li>
                    <li class="dropdown">
                      <button type="button" name="button" class="dropdown-toggle btn btn-default" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        <%= fa_icon("ellipsis-h") %>
                      </button>
                      <ul class="dropdown-menu" style="margin-top:7px;">
                        <li><a href="#">Edit sprint</a></li>
                        <li><%= link_to "Delete sprint", project_board_sprint_path(@project_id, @board_id, sprint), method: :delete, data: {confirm: "Are you sure?"} %></li>
                      </ul>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <table class="table table-striped" style="margin-top:15px;">
              <tr>
                <td class="text-center">-</td>
              </tr>
            </table>
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <%= link_to "Create issue", issue_project_board_path(@project_id, @board_id), class: "btn btn-info" %>
            <div id="form-create-issue" style="width:350px;margin-top:10px;display:none;">
              <!-- type-issue -->
              <select class="form-control" name="" style="width:80px;float:left;">

              </select>


              <!-- choose-sprint -->
              <div class="" style="margin-left:10px;float:left;">
                <!-- what-need-tobe-dones -->
                <input type="text" class="form-control" name="" value="" placeholder="what need to be done ?" style="width:200px;">
                <select class="form-control" name="" style="margin-top:10px;width:200px;">
                  <option value="0">backlog</option>
                </select>
              </div>
            </div>
          </div>
        </div>
      </div>
      <hr>
    <% end %>

    <!-- ################################################################## -->

    <div class="main-backlog" style="padding-bottom:100px;font-family: 'Open Sans', sans-serif;">
      <div class="row">
        <div class="col-md-6">
          <h4>Backlog</h4>
        </div>
        <div class="col-md-6">
          <%= link_to "Create sprint", project_board_sprints_path(@project_id, @board_id), class: "btn btn-primary", style: "float: right;", method: :post %>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <table class="table table-striped" style="margin-top:15px;">
            <% @backlog.each do |backlog| %>
              <tr>
                <td><label class="label label-warning"><%= backlog.title_issue.upcase %></label></td>
                <td><label class="label label-primary"><%= backlog.list.title.upcase %></label></td>
                <td><%= backlog.title %></td>
                <td><label class="label label-primary"><%= backlog.title_priority.upcase %></label></td>
                <td><%= backlog.duedate.strftime("%m/%d/%Y") %></td>
                <td>
                  <%= link_to edit_project_board_card_path(params[:project_id], params[:id], backlog), class: "btn btn-xs btn-default" do %>
                    <%= fa_icon("pencil") %>
                  <% end %>

                  <%= link_to issue_project_board_path(params[:project_id], params[:id], backlog), class: "btn btn-xs btn-default", method: :delete, data: {confirm: "Are you sure ?"} do %>
                    <%= fa_icon("trash") %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <%= link_to "Create issue", issue_project_board_path(@project_id, @board_id), class: "btn btn-info" %>

          <div id="form-create-issue" style="width:350px;margin-top:10px;display:none">
            <!-- type-issue -->
            <select class="form-control" name="" style="width:80px;float:left;">
              <% @typeissue.each do |issue| %>
                <option value=""><%= issue.name %></option>
              <% end %>
            </select>


            <!-- choose-sprint -->
            <div class="" style="margin-left:10px;float:left;">
              <!-- what-need-tobe-dones -->
              <input type="text" class="form-control" name="" value="" placeholder="what need to be done ?" style="width:200px;">
              <select class="form-control" name="" style="margin-top:10px;width:200px;">
                <option value="0">Backlog</option>
                <% @sprint.each do |sprint| %>
                  <option value=""><%= sprint.name %></option>
                <% end %>
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>